config/routes.rb
Rails.application.routes.draw do
  resources :trails
  resources :topics

  root 'trails#index'

  resources :topics do
    member do
      post 'upvote'
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :votes, dependent: :destroy
end

app/models/trail.rb
class Trail < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote 
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  before_action :set_trail, only: [:show, :edit, :update, :destroy]

  # GET /trails
  # GET /trails.json
  def index
    @trails = Trail.all
  end

  # GET /trails/1
  # GET /trails/1.json
  def show
  end

  # GET /trails/new
  def new
    @trail = Trail.new
  end

  # GET /trails/1/edit
  def edit
  end

  # POST /trails
  # POST /trails.json
  def create
    @trail = Trail.new(trail_params)

    respond_to do |format|
      if @trail.save
        format.html { redirect_to @trail, notice: 'Trail was successfully created.' }
        format.json { render :show, status: :created, location: @trail }
      else
        format.html { render :new }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trails/1
  # PATCH/PUT /trails/1.json
  def update
    respond_to do |format|
      if @trail.update(trail_params)
        format.html { redirect_to @trail, notice: 'Trail was successfully updated.' }
        format.json { render :show, status: :ok, location: @trail }
      else
        format.html { render :edit }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trails/1
  # DELETE /trails/1.json
  def destroy
    @trail.destroy
    respond_to do |format|
      format.html { redirect_to trails_url, notice: 'Trail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trail
      @trail = Trail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trail_params
      params.require(:trail).permit(:name, :idNum)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CounterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.description %></td>
        <td><%= pluralize(topic.votes.count, "vote") %></td>
        <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/trails/_form.html.erb
<%= form_for(@trail) do |f| %>
  <% if @trail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trail.errors.count, "error") %> prohibited this trail from being saved:</h2>

      <ul>
      <% @trail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :idNum %><br>
    <%= f.number_field :idNum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trails/edit.html.erb
<h1>Editing Trail</h1>

<%= render 'form' %>

<%= link_to 'Show', @trail %> |
<%= link_to 'Back', trails_path %>

app/views/trails/index.html.erb
<p id="notice"><%= notice %></p>
<div class="navContainer">
  <h2 class="title">AllTrails Calorie Counter</h2>
  <div class="nav"></div>
</div>
<div class="infoContainer">
  <div class="aboutTitleContainer">
    <label class="aboutYouLabel">About You</label>
  

    <table class="inputTable">
      <tr>
        <td><label>Weight (lbs)</label></td>
        <td><input type="range" name="pounds" id="weight" value="150" min="75" max="300" step="5.0"></td>
        <td><label id="weightLabel" class="displayInfo">150 pounds</label></td>
      </tr>
      <tr>
        <td><label>Pace (MPH)</label></td>
        <td><input type="range" name="pace" id="speed" value="1" min="0" max="12" step="0.5"></td>
        <td><label id="speedLabel" class="displayInfo">1 MPH</label></td>
      </tr>
      <tr>
        <td><label>Age</label></td>
        <td><input type="range" name="age" id="ageEntry" value="23" min="10" max="120" step="1"></td>
        <td><label id="ageLabel" class="displayInfo">23 years old</label></td>
      </tr>
    </table>
  </div>
  <hr>
  <label class="aboutYouLabel">Select Your Trail</label>
  <div class="trailContainer">
    <select id="trailPicker">
      <% @trails.each do |eachtrail| %>
        <%= content_tag(:option, eachtrail.name, value: eachtrail.idNum) %>
      <% end %>
    </select>
    <label id="distanceLabel" class="displayInfo">0 Miles</label>
    <label id="elevationLabel" class="displayInfo">0 feet gained</label>
  </div>
  <hr>
  <h2 id="calorieLabel">0 calories burned!</h2>
  <%= link_to 'New Trail', new_trail_path %>
</div>
<br>

app/views/trails/new.html.erb
<h1>New Trail</h1>

<%= render 'form' %>

<%= link_to 'Back', trails_path %>

app/views/trails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trail.name %>
</p>

<p>
  <strong>Idnum:</strong>
  <%= @trail.idNum %>
</p>

<%= link_to 'Edit', edit_trail_path(@trail) %> |
<%= link_to 'Back', trails_path %>